#%RAML 1.0 NamedExample
value:
  -
    order_id: 977
    customer_id: 'CUSMLY0098'
    address_id: 'MLYKLM0032'
    order_items_count: 2
    order_total_price: 555.44
    order_created_date: '2019-11-26 07:27:40'
  -
    order_id: 1001
    customer_id: 'CUSIND0098'
    address_id: 'INDDEL0032'
    order_items_count: 1
    order_total_price: 200.00
    order_created_date: '2019-11-26 07:27:40'